Return-Path: <osmocom-net-gprs-bounces@lists.osmocom.org>
X-Original-To: lists+osmocom-net-gprs@lfdr.de
Delivered-To: lists+osmocom-net-gprs@lfdr.de
Received: from lists.osmocom.org (lists.osmocom.org [IPv6:2a01:4f8:191:444b::2:7])
	by mail.lfdr.de (Postfix) with ESMTP id 28FB6439AD1
	for <lists+osmocom-net-gprs@lfdr.de>; Mon, 25 Oct 2021 17:50:17 +0200 (CEST)
Received: from lists.osmocom.org (lists.osmocom.org [144.76.43.76])
	by lists.osmocom.org (Postfix) with ESMTP id 536FA217DE8;
	Mon, 25 Oct 2021 15:50:14 +0000 (UTC)
Authentication-Results: lists.osmocom.org; dmarc=none (p=none dis=none) header.from=osmocom.org
X-Original-To: osmocom-net-gprs@lists.osmocom.org
Delivered-To: osmocom-net-gprs@lists.osmocom.org
Received-SPF: Pass (mailfrom) identity=mailfrom;
 client-ip=2001:780:45:1d:225:90ff:fe52:c662; helo=ganesha.gnumonks.org;
 envelope-from=laforge@osmocom.org; receiver=<UNKNOWN> 
Authentication-Results: lists.osmocom.org;
 dmarc=none (p=none dis=none) header.from=osmocom.org
Received: from ganesha.gnumonks.org (ganesha.gnumonks.org
 [IPv6:2001:780:45:1d:225:90ff:fe52:c662])
 by lists.osmocom.org (Postfix) with ESMTP id 91B14217DBF
 for <osmocom-net-gprs@lists.osmocom.org>; Mon, 25 Oct 2021 15:50:04 +0000 (UTC)
Received: from uucp by ganesha.gnumonks.org with local-bsmtp (Exim 4.89)
 (envelope-from <laforge@osmocom.org>)
 id 1mf2Ee-00052l-BM; Mon, 25 Oct 2021 17:50:04 +0200
Received: from laforge by localhost.localdomain with local (Exim 4.95)
 (envelope-from <laforge@osmocom.org>) id 1mf2BM-00DPC3-5m;
 Mon, 25 Oct 2021 17:46:40 +0200
Date: Mon, 25 Oct 2021 17:46:40 +0200
From: Harald Welte <laforge@osmocom.org>
To: Mirko Kovacevic <northmirko@gmail.com>
Cc: osmocom-net-gprs@lists.osmocom.org
Subject: Re: TTCN-3 tests for MME
Message-ID: <YXbRYNTFS+5z8Tyi@nataraja>
References: <CAMYWRL_Bn9TzSL6vAdzA=E8oK8hEWtYTP890dHg1JVd0g5b_pA@mail.gmail.com>
 <CAMYWRL_ibx+Z-CrV2vqytLEuU5PWfLr7yDkG54OnBNkbmWahyQ@mail.gmail.com>
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Disposition: inline
In-Reply-To: <CAMYWRL_ibx+Z-CrV2vqytLEuU5PWfLr7yDkG54OnBNkbmWahyQ@mail.gmail.com>
X-BeenThere: osmocom-net-gprs@lists.osmocom.org
X-Mailman-Version: 2.1.34
Precedence: list
List-Id: "Discussion on the Osmocom network-side GPRS components like OsmoPCU,
 OsmoSGSN" <osmocom-net-gprs.lists.osmocom.org>
List-Unsubscribe: <https://lists.osmocom.org/mailman/options/osmocom-net-gprs>, 
 <mailto:osmocom-net-gprs-request@lists.osmocom.org?subject=unsubscribe>
List-Archive: <http://lists.osmocom.org/pipermail/osmocom-net-gprs/>
List-Post: <mailto:osmocom-net-gprs@lists.osmocom.org>
List-Help: <mailto:osmocom-net-gprs-request@lists.osmocom.org?subject=help>
List-Subscribe: <https://lists.osmocom.org/mailman/listinfo/osmocom-net-gprs>, 
 <mailto:osmocom-net-gprs-request@lists.osmocom.org?subject=subscribe>
Errors-To: osmocom-net-gprs-bounces@lists.osmocom.org
Sender: "osmocom-net-gprs" <osmocom-net-gprs-bounces@lists.osmocom.org>

On Fri, Oct 22, 2021 at 02:12:03PM +0200, Mirko Kovacevic wrote:
> Protocol-IEs, MMEname and ENBname, cant be decoded\encoded properly,
> definitely.

one would have to check if the encoding problem already exists in the BER version
(as generated by TITAN natively) or if it happens at the BER <-> PER transcoding
inside the [unfortunately] non-public libfftranscode, generated by ffasn1c.

I you can build a small, self contained test case that shows a problem in 
BER <-> PER transcoding using the libfftranscode API directly (removing all of TITAN, etc.)
then we may have a chance of either solving it at sysmocom or by asking
the ffasn1c author to have a look

> Amazing progress with S1AP emulation, congrats.

thanks.  Please keep us posted about any progress.  We're happy to merge any
related patches  you may have for adding more test cases, fixing bugs, etc.

I never found the time for it, but the general idea always was to automatically
run this testsuite in jenkins.osmocom.org against the open5gs-mme, like we do
for or own osmocom software.

Regards,
	Harald
-- 
- Harald Welte <laforge@osmocom.org>            http://laforge.gnumonks.org/
============================================================================
"Privacy in residential applications is a desirable marketing option."
                                                  (ETSI EN 300 175-7 Ch. A6)
